apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30080   #kubernetes restriction, it should be greater then 30,000
  
  type: NodePort
